### ISSUE TITLE
Error CV_RGB2Lab

### ISSUE THREAD

**Issue by diogocaribe** [cbalint13/gdal-segment#10]
I have this error when I was installing lib. How to corret it?
My SO is Ubuntu 16.04.

sudo make
[ 25%] Building CXX object src/CMakeFiles/gdal-segment.dir/gdal-segment.cpp.o
/home/diogocaribe/gdal-segment/src/gdal-segment.cpp: In function ‘int main(int, char**)’:
/home/diogocaribe/gdal-segment/src/gdal-segment.cpp:291:25: error: ‘CV_RGB2Lab’ was not declared in this scope
     cvtColor( rgb, lab, CV_RGB2Lab );
                         ^
src/CMakeFiles/gdal-segment.dir/build.make:110: recipe for target 'src/CMakeFiles/gdal-segment.dir/gdal-segment.cpp.o' failed
make[2]: *** [src/CMakeFiles/gdal-segment.dir/gdal-segment.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'src/CMakeFiles/gdal-segment.dir/all' failed
make[1]: *** [src/CMakeFiles/gdal-segment.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bozhidarc** [comment]
I'm expericieng the same problem. Did you manage to resolve it ?

Here is my cmake output

```
-- The C compiler identification is GNU 5.5.0
-- The CXX compiler identification is GNU 5.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp
-- OpenMP found.
-- Found OpenCV: /usr/local (found version "4.0.0") found components:  core ximgproc hdf
-- OpenCV version: 4.0.0
-- OpenCV include: /usr/local/include/usr/local/include/opencv
-- Found GDAL: /usr/local/lib/libgdal.so
-- GDAL found.
-- GDAL version: 2.2.3
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/gdal-segment/build
```

**Comment by bozhidarc** [comment]
Ok, I included manulay `#include <opencv2/imgproc/types_c.h>` in `gdal-segment/src/gdal-segment.cpp`.
