### ISSUE TITLE
How to define type of output vector (e.g. line) and its georeference?

### ISSUE THREAD

**Issue by SCrommelinck** [cbalint13/gdal-segment#13]
I am wondering if it is possible to save the output vector file with the same georeference as the source raster file. When I open the output vector file in QGIS, I still have to define the coordinate reference system.

Further, I would like to save the output as a line vector layer instead of as polygons. I cannot find further info on which other options the parameter `[-of <output_format> 'ESRI Shapefile' is default] ` allows and if saving the output as a line vector layer would be possible.

Thank you in advance.

**Comment by diogocaribe** [comment]
@SCrommelinck 

I had the same problem but I think that the problem not to gdal-segment. 

It looks like that gdal has one bug.  See this topic https://gis.stackexchange.com/questions/280346/why-ogr-doesnt-read-this-kind-of-prj.

Regards

**Comment by its4land** [comment]
@diogocaribe okay, so maybe a workaround might be to have a script reading the prj information from the raster file and writing that to the vector file.
@cbalint13 could you provide information on possible values for the `-of` parameter?

**Comment by SCrommelinck** [comment]
@diogocaribe so maybe a workaround might be to write a script that reads the prj info from the raster file and writes it to the vector file.

@cbalint13 could you provide info on which values (e.g. lines) can be set for the `-of` parameter?

**Comment by diogocaribe** [comment]
@SCrommelinck  You can delete the .prj file and define projection again - with the same data as the original file. I did it in qgis and it works well. Not the best solution, but work.

The only output geometry in -of is polygon. If you would like to convert polygons to line is one way to solve your problem.
