### ISSUE TITLE
Utilizing GPU via OpenCV built against Cuda?

### ISSUE THREAD

**Issue by PeterSprague** [cbalint13/gdal-segment#7]
Generating superpixels on larger orthophotos can take hours.  

I am running gdal-segment inside a nvidia:cuda based docker container.  OpenCV was built with Cuda capabilities, yet nvidia-smi shows no GPU processing attributable to gdal-segment.  Has the code been written to utilize Cuda?

**Comment by cbalint13** [comment]
No. The very OpenCV's superpixel routines are CPU only for now.
